apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primecx-ingress
  namespace: primecx
  labels:
    app.kubernetes.io/part-of: primecx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:ACCOUNT_ID:certificate/CERTIFICATE_ID
spec:
  tls:
    - hosts:
        - primecx.example.com
      secretName: primecx-tls
  rules:
    - host: primecx.example.com
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: primecx-backend
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: primecx-frontend
                port:
                  number: 80
