apiVersion: v1
kind: ServiceAccount
metadata:
  name: primecx-backend
  namespace: primecx
  labels:
    app: primecx-backend
    app.kubernetes.io/part-of: primecx
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/primecx-backend-role
