package com.primecx.model;

public enum AuditEventType {
    ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    USER_PROFILE_UPDATED,
    USER_ORGANIZATION_ASSIGNED,
    SESSION_ENDED,
    RECORDING_CONFIRMED,
    RECORDING_SOFT_DELETED,
    RECORDING_LEGAL_HOLD_CHANGED,
    RETENTION_POLICY_UPSERTED
}
